version: 2
jobs:
  build:
    working_directory: ~/reddit-redux
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - run:
          name: Install Dependencies
          command: yarn ci

      - save_cache:
          paths:
            - /home/circleci/.yarn
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Run Tests
          command: yarn test