version: 2
jobs:
  build:
    working_directory: ~/reddit-redux
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Run Tests
          command: yarn test